name       : libdbusmenu
version    : 16.04.0
release    : 1
source     :
    - https://launchpad.net/libdbusmenu/16.04/16.04.0/+download/libdbusmenu-16.04.0.tar.gz : b9cc4a2acd74509435892823607d966d424bd9ad5d0b00938f27240a1bfa878a
license    :
    - GPL-3.0
    - LGPL-2.1
component  : programming.library
summary    : D-BUS Menu Library
description: |
    A small little library that was created by pulling out some comon code out of indicator-applet. It passes a menu structure across DBus so that a program can create a menu simply without worrying about how it is displayed on the other side of the bus.
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig32(gio-unix-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig32(gtk+-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig32(json-glib-1.0)
    - pkgconfig32(atk)
    - pkgconfig32(xshmfence)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
setup      : |
    %configure --disable-static --with-gtk=2 --prefix=/usr
build      : |
    %make
install    : |
    %make_install
